### ISSUE TITLE
compatibility with nvidia driver version 511.17

### ISSUE THREAD

**Issue by mikekoo** [shamskv/EZVIDIA#6]
recently updated to nvidia driver 511.17 and when trying to save or switch to a saved config I get an error:

Problem retrieving configuration

Anyone else having this error message?

**Comment by shamskv** [comment]
I'm not able to reproduce this problem consistently. I have a 2060 so no 511.17 or above for me.  I do have access to Studio Drivers 511.09 so I installed those.

I was able to reproduce the error *right* after installing the drivers, but I followed that with a PC restart. And since then I never got the error again.

I still have some ideas to help you fix this issue, but before trying those could you let me know if you have already tried it after a full reboot?

**Comment by mikekoo** [comment]
Thank you so much! That resolved my issue.  I'm sorry for not trying a reboot before submitting this issue.  Hopefully it helps someone in the future.  Thank you for the awesome application!
